### ISSUE TITLE
License

### ISSUE THREAD

**Issue by haesleinhuepf** [INRAE-LPGP/ImageAnalysis_CombineLabels#1]
Hi  @M4n0-LES @VThermes ,

I just read your paper and was amazed that the code is openly available. Thanks for this! However, in order to allow others to reuse it, it would be great to add a license file to it. If you need assistance with that, https://choosealicense.com/ can help.

Thanks!

Best,
Robert

**Comment by mlesage-bioimage** [comment]
Hi @haesleinhuepf ,
Thanks for the advice, I've just added a MIT licence.

Best,
Manon
